@startuml
' 図書館システム

' 利用者
' 会員ID, 氏名, 区分（学生/教職員）, 学籍番号/職員番号
[利用者] o-- [会員ID]
[利用者] o-- [氏名]
[利用者] o-- [区分]
[利用者] o-- [学籍番号/職員番号]

' 資料
' 管理番号, タイトル, 区分（書籍/雑誌）
[資料] o-- [管理番号]
[資料] o-- [タイトル]
[資料] o-- [区分]

' 貸出
' 貸出日, 返却期限, 返却日
[貸出] o-- [利用者]
[貸出] o-- [資料]
[貸出] o-- [貸出日]
[貸出] o-- [返却期限]
[貸出] o-- [返却日]

' 予約
' 予約日, 状態
[予約] o-- [利用者]
[予約] o-- [資料]
[予約] o-- [予約日]
[予約] o-- [状態]

' 貸出履歴
' 利用者ID, 資料ID, 貸出日, 返却日
[貸出履歴] o-- [利用者ID]
[貸出履歴] o-- [資料ID]
[貸出履歴] o-- [貸出日]
[貸出履歴] o-- [返却日]

@enduml
